language: generic
services:
  - docker
before_install:
  - make build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: make push
  on:
    branch: master
